In [1]:
import numpy as np

In [2]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [3]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [4]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [5]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [6]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [10]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [11]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [13]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
arr2d[2]

array([7, 8, 9])

In [15]:
arr2d[0][2]

3

In [16]:
arr2d[0,2]

3

In [26]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [28]:
arr3d[0][1]

array([4, 5, 6])

In [29]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr3d.shape

(2, 2, 3)

In [32]:
names = np.array(['Olek','Anna','Piotr','Leon','Anna','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Olek', 'Anna', 'Piotr', 'Leon', 'Anna', 'Jan', 'Jan'], dtype='%lt;U5')

In [33]:
data

array([[-0.85101195, -0.36197409, 1.39321099, -0.55830266],
 [ 1.28090243, 3.39322591, -0.86129313, -0.05087409],
 [-0.67577764, -0.52916927, -1.13411162, -1.01420685],
 [-1.02577158, -2.56894782, -1.78034035, -1.84451656],
 [-0.19363514, 0.2366924 , -0.1841167 , 1.44458982],
 [ 0.70452807, -0.77478191, 0.07238382, 2.85664017],
 [ 0.05149974, -0.33377097, 0.61598203, 0.26559879]])

In [34]:
names == "Jan"

array([False, False, False, False, False, True, True])

In [35]:
data[names=="Jan"]

array([[ 0.70452807, -0.77478191, 0.07238382, 2.85664017],
 [ 0.05149974, -0.33377097, 0.61598203, 0.26559879]])