In [59]:
import numpy as np

In [60]:
arr = np.random.randn(5,4)
arr

array([[ 4.71435164e-01, -1.19097569e+00, 1.43270697e+00,
 -3.12651896e-01],
 [-7.20588733e-01, 8.87162940e-01, 8.59588414e-01,
 -6.36523504e-01],
 [ 1.56963721e-02, -2.24268495e+00, 1.15003572e+00,
 9.91946022e-01],
 [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
 2.11836468e-03],
 [ 4.05453412e-01, 2.89091941e-01, 1.32115819e+00,
 -1.54690555e+00]])

In [61]:
arr.mean()

-0.0112972439581026

In [62]:
arr.mean(axis=0)

array([ 0.22506407, -0.85573212, 0.88588239, -0.30040331])

In [63]:
arr = np.array([1,2,4,5,6,7,9,11,22])
arr.cumsum()

array([ 1, 3, 7, 12, 18, 25, 34, 45, 67])

In [64]:
arr.cumprod()

array([ 1, 2, 8, 40, 240, 1680, 15120,
 166320, 3659040])

In [65]:
arr = np.array([[0,1,2],[6,7,8],[10,15,19]])
arr

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [10, 15, 19]])

In [66]:
arr.cumsum(axis=1)

array([[ 0, 1, 3],
 [ 6, 13, 21],
 [10, 25, 44]])

In [67]:
arr.cumprod(axis=0)

array([[ 0, 1, 2],
 [ 0, 7, 16],
 [ 0, 105, 304]])

In [68]:
arr = np.random.randn(100)
(arr>0).sum()

57

In [69]:
bools = np.array([False,True,True,False])
bools.any()

True

In [70]:
bools.all()

False

In [71]:
names = np.array(['Jan','Anna','Henryk','Jan','Anna','Anna','Olaf'])
np.unique(names)

array(['Anna', 'Henryk', 'Jan', 'Olaf'], dtype='%lt;U6')

In [72]:
lb = np.array([3,5,6,7,1,2,3,4,2,3,4,5,2,3,4])
u = np.unique(lb)
print(u)

[1 2 3 4 5 6 7]


In [73]:
#sorted(u)

In [74]:
print(u)

[1 2 3 4 5 6 7]


In [75]:
u.sort()
u

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
sorted(names)

['Anna', 'Anna', 'Anna', 'Henryk', 'Jan', 'Jan', 'Olaf']

In [77]:
names

array(['Jan', 'Anna', 'Henryk', 'Jan', 'Anna', 'Anna', 'Olaf'],
 dtype='%lt;U6')

In [78]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False, True, True, False, True])

In [79]:
#algebra liniowa
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
x

array([[1., 2., 3.],
 [4., 5., 6.]])

In [80]:
y

array([[ 6., 23.],
 [-1., 7.],
 [ 8., 9.]])

In [81]:
np.dot(x,y)

array([[ 28., 64.],
 [ 67., 181.]])

In [82]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [83]:
x @ np.ones(3)

array([ 6., 15.])

In [84]:
#generowanie liczb pseudolosowych
sample = np.random.normal(size=(4,4))
sample

array([[-0.24843205, -0.61770665, -0.682884 , 0.4362576 ],
 [-1.70301277, 0.3937106 , -0.479324 , -0.29901629],
 [ 0.69410329, 0.67862967, 0.239556 , 0.15122663],
 [ 0.81612723, 1.89353447, 0.63963276, -0.96202883]])

In [85]:
from random import normalvariate

N = 1000000
%timeit sample = [normalvariate(0,1) for _ in range(N)]
%timeit np.random.normal(size=N)

1.09 s ± 8.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
33.8 ms ± 36.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [94]:
np.random.seed(987)
rng = np.random.RandomState(987)
rng.randn(10)

array([-1.68592706, -1.47111992, -0.11180006, 1.03636979, 0.66103991,
 0.88291241, -1.08332763, -0.84713169, 0.15827816, 0.09909731])