In [2]:
import numpy as np

In [3]:
arr = np.random.randn(5,4)
arr

array([[ 0.08913938, -0.16469465, 1.46667678, -0.39130447],
 [-0.66611074, 0.09265858, 0.4767354 , 0.27715368],
 [ 0.27538413, 0.67518878, -0.29460084, 0.59534853],
 [-2.04264971, -2.19134684, 0.26422676, 0.60761024],
 [ 0.12892409, -1.45942674, -1.40324637, 0.81663416]])

In [4]:
arr.mean()

-0.14238499313352665

In [6]:
arr.mean(axis=0)

array([-0.44306257, -0.60952418, 0.10195835, 0.38108843])

In [9]:
arr = np.array([1,2,4,5,6,7,9,11,22])
arr.cumsum()

array([ 1, 3, 7, 12, 18, 25, 34, 45, 67])

In [10]:
arr.cumprod()

array([ 1, 2, 8, 40, 240, 1680, 15120,
 166320, 3659040])

In [11]:
arr = np.array([[0,1,2],[6,7,8],[10,15,19]])
arr

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [10, 15, 19]])

In [13]:
arr.cumsum(axis=1)

array([[ 0, 1, 3],
 [ 6, 13, 21],
 [10, 25, 44]])

In [15]:
arr.cumprod(axis=0)

array([[ 0, 1, 2],
 [ 0, 7, 16],
 [ 0, 105, 304]])

In [20]:
arr = np.random.randn(100)
(arr>0).sum()

54

In [30]:
bools = np.array([False,True,True,False])
bools.any()

True

In [31]:
bools.all()

False

In [32]:
names = np.array(['Jan','Anna','Henryk','Jan','Anna','Anna','Olaf'])
np.unique(names)

array(['Anna', 'Henryk', 'Jan', 'Olaf'], dtype='%lt;U6')

In [45]:
lb = np.array([3,5,6,7,1,2,3,4,2,3,4,5,2,3,4])
u = np.unique(lb)
print(u)

[1 2 3 4 5 6 7]


In [37]:
#sorted(u)

[1, 2, 3, 4, 5, 6, 7]

In [44]:
print(u)

[1 2 3 4 5 6 7]


In [43]:
u.sort()
u

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
sorted(names)

['Anna', 'Anna', 'Anna', 'Henryk', 'Jan', 'Jan', 'Olaf']

In [47]:
names

array(['Jan', 'Anna', 'Henryk', 'Jan', 'Anna', 'Anna', 'Olaf'],
 dtype='%lt;U6')

In [49]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False, True, True, False, True])