In [1]:
import numpy as np

In [2]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [3]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [4]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [5]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [6]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [7]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [8]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [9]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arr2d[2]

array([7, 8, 9])

In [11]:
arr2d[0][2]

3

In [12]:
arr2d[0,2]

3

In [13]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [15]:
arr3d[0][1]

array([4, 5, 6])

In [16]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d.shape

(2, 2, 3)

In [19]:
names = np.array(['Olek','Anna','Piotr','Leon','Anna','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Olek', 'Anna', 'Piotr', 'Leon', 'Anna', 'Jan', 'Jan'], dtype='%lt;U5')

In [20]:
data

array([[ 0.16827572, 1.17383156, 1.9727632 , -1.32800988],
 [-0.85970249, 0.64334126, 0.29878689, 1.87331764],
 [ 1.86538248, 1.23927297, 0.7755612 , 0.5611396 ],
 [ 0.65172418, 1.45431321, -0.07199224, 0.36646283],
 [ 1.78018179, 0.89018478, -1.16214207, 0.47441752],
 [ 0.37440298, -0.0362738 , 0.37984329, -0.15988767],
 [ 0.01237244, -1.18490508, -1.10705937, -1.14475921]])

In [21]:
names == "Jan"

array([False, False, False, False, False, True, True])

In [22]:
data[names=="Jan"]

array([[ 0.37440298, -0.0362738 , 0.37984329, -0.15988767],
 [ 0.01237244, -1.18490508, -1.10705937, -1.14475921]])

In [23]:
cond = names == "Jan"
data[~cond]

array([[ 0.16827572, 1.17383156, 1.9727632 , -1.32800988],
 [-0.85970249, 0.64334126, 0.29878689, 1.87331764],
 [ 1.86538248, 1.23927297, 0.7755612 , 0.5611396 ],
 [ 0.65172418, 1.45431321, -0.07199224, 0.36646283],
 [ 1.78018179, 0.89018478, -1.16214207, 0.47441752]])

In [24]:
mask = (names == "Jan") | (names == "Anna")
mask

array([False, True, False, False, True, True, True])

In [25]:
data[mask]

array([[-0.85970249, 0.64334126, 0.29878689, 1.87331764],
 [ 1.78018179, 0.89018478, -1.16214207, 0.47441752],
 [ 0.37440298, -0.0362738 , 0.37984329, -0.15988767],
 [ 0.01237244, -1.18490508, -1.10705937, -1.14475921]])

In [26]:
data[data<0] =0
data

array([[0.16827572, 1.17383156, 1.9727632 , 0. ],
 [0. , 0.64334126, 0.29878689, 1.87331764],
 [1.86538248, 1.23927297, 0.7755612 , 0.5611396 ],
 [0.65172418, 1.45431321, 0. , 0.36646283],
 [1.78018179, 0.89018478, 0. , 0.47441752],
 [0.37440298, 0. , 0.37984329, 0. ],
 [0.01237244, 0. , 0. , 0. ]])

In [27]:
data[names!="Olek"] = 8
data

array([[0.16827572, 1.17383156, 1.9727632 , 0. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ]])