In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import matplotlib.pyplot as plt

In [2]:
obj = pd.Series([4,-5,9,4,-6])
obj

0 4
1 -5
2 9
3 4
4 -6
dtype: int64

In [3]:
obj.values

array([ 4, -5, 9, 4, -6])

In [4]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
obj2 = pd.Series([45,6,8,9,12,45,17], index=['a','b','c','d','e','f','g'])
obj2

a 45
b 6
c 8
d 9
e 12
f 45
g 17
dtype: int64

In [6]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [7]:
obj2['g']

17

In [8]:
obj2['a'] = 222
obj2

a 222
b 6
c 8
d 9
e 12
f 45
g 17
dtype: int64

In [9]:
obj2[obj2>10]

a 222
e 12
f 45
g 17
dtype: int64

In [10]:
sdata = {'Warszawa':45673,'Kraków':38999,'Lublin':31450,'Gdańsk':34525}
obj3 = pd.Series(sdata)
obj3

Warszawa 45673
Kraków 38999
Lublin 31450
Gdańsk 34525
dtype: int64

In [11]:
miasta = ['Poznań','Kraków','Rzeszów','Lublin']
obj4 = pd.Series(sdata,index=miasta)
obj4

Poznań NaN
Kraków 38999.0
Rzeszów NaN
Lublin 31450.0
dtype: float64

In [13]:
pd.isnull(obj4)

Poznań True
Kraków False
Rzeszów True
Lublin False
dtype: bool

In [14]:
obj3+obj4

Gdańsk NaN
Kraków 77998.0
Lublin 62900.0
Poznań NaN
Rzeszów NaN
Warszawa NaN
dtype: float64

In [17]:
obj4.name = 'liczba wniosków'
obj4.index.name = 'miasta'
obj4

miasta
Poznań NaN
Kraków 38999.0
Rzeszów NaN
Lublin 31450.0
Name: liczba wniosków, dtype: float64

In [18]:
data = {
    'miasto':['Warszawa','Warszawa','Warszawa','Kraków','Kraków','Kraków'],
    'rok':[2017,2018,2019,2018,2019,2020],
    'pop':[2.7,2.75,3.05,0.85,0.9,1.01]
}

frame = pd.DataFrame(data)
frame

miasto 
 rok 
 pop 
 
 
 
 
 0 
 Warszawa 
 2017 
 2.70 
 
 
 1 
 Warszawa 
 2018 
 2.75 
 
 
 2 
 Warszawa 
 2019 
 3.05 
 
 
 3 
 Kraków 
 2018 
 0.85 
 
 
 4 
 Kraków 
 2019 
 0.90 
 
 
 5 
 Kraków 
 2020 
 1.01

In [21]:
frame2 = pd.DataFrame(data,columns=['rok','miasto','pop','wsp'],index=['jeden','dwa','trzy',
                                                                       'cztery','pieć','sześć'])

frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 NaN 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 NaN 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 NaN 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 NaN 
 
 
 pieć 
 2019 
 Kraków 
 0.90 
 NaN 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 NaN

In [22]:
frame2['miasto']

jeden Warszawa
dwa Warszawa
trzy Warszawa
cztery Kraków
pieć Kraków
sześć Kraków
Name: miasto, dtype: object

In [24]:
frame2.rok

jeden 2017
dwa 2018
trzy 2019
cztery 2018
pieć 2019
sześć 2020
Name: rok, dtype: int64

In [25]:
frame2['wsp']=19.9

In [26]:
frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 19.9 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 19.9 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 19.9 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 19.9 
 
 
 pieć 
 2019 
 Kraków 
 0.90 
 19.9 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 19.9

In [27]:
frame2['wsp'] =  np.arange(6.)
frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 0.0 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 1.0 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 2.0 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 3.0 
 
 
 pieć 
 2019 
 Kraków 
 0.90 
 4.0 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 5.0

In [31]:
daty = pd.date_range("20230217",periods=6)
daty

DatetimeIndex(['2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22'],
              dtype='datetime64[ns]', freq='D')

In [32]:
fr = pd.DataFrame(np.random.randn(6,4),index=daty,columns=list("ABCD"))
fr

A 
 B 
 C 
 D 
 
 
 
 
 2023-02-17 
 0.761400 
 1.623861 
 -1.884717 
 -1.134514 
 
 
 2023-02-18 
 -0.704839 
 1.160876 
 1.274615 
 -0.001083 
 
 
 2023-02-19 
 0.120918 
 -0.347559 
 -0.101633 
 0.406643 
 
 
 2023-02-20 
 -0.229092 
 0.838557 
 0.552787 
 1.496969 
 
 
 2023-02-21 
 0.843114 
 0.854012 
 -0.478044 
 0.169175 
 
 
 2023-02-22 
 0.475302 
 1.313454 
 0.239601 
 0.238632

In [34]:
fr.head(3)

A 
 B 
 C 
 D 
 
 
 
 
 2023-02-17 
 0.761400 
 1.623861 
 -1.884717 
 -1.134514 
 
 
 2023-02-18 
 -0.704839 
 1.160876 
 1.274615 
 -0.001083 
 
 
 2023-02-19 
 0.120918 
 -0.347559 
 -0.101633 
 0.406643

In [35]:
fr.tail(2)

A 
 B 
 C 
 D 
 
 
 
 
 2023-02-21 
 0.843114 
 0.854012 
 -0.478044 
 0.169175 
 
 
 2023-02-22 
 0.475302 
 1.313454 
 0.239601 
 0.238632

In [38]:
nfr = fr.to_numpy()
print(nfr)
print(type(fr))
print(type(nfr))

[[ 7.61400382e-01  1.62386121e+00 -1.88471744e+00 -1.13451359e+00]
 [-7.04838774e-01  1.16087567e+00  1.27461491e+00 -1.08288172e-03]
 [ 1.20918050e-01 -3.47559327e-01 -1.01633498e-01  4.06642654e-01]
 [-2.29092172e-01  8.38557111e-01  5.52787447e-01  1.49696937e+00]
 [ 8.43114152e-01  8.54011796e-01 -4.78044138e-01  1.69175391e-01]
 [ 4.75301860e-01  1.31345373e+00  2.39600832e-01  2.38631641e-01]]
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [44]:
frc = fr.to_csv(r"c:\\Temp\\dane.csv")

In [45]:
f = open(r"c:\\Temp\\dane.csv","r")
print(f.read())

,A,B,C,D
2023-02-17,0.7614003821997798,1.6238612067051068,-1.8847174429911402,-1.1345135856913782
2023-02-18,-0.7048387736087316,1.1608756696730058,1.2746149149834443,-0.0010828817161149542
2023-02-19,0.12091805007801856,-0.3475593271873022,-0.10163349828692254,0.4066426537438583
2023-02-20,-0.22909217198341092,0.8385571106459146,0.5527874466606277,1.4969693681110356
2023-02-21,0.8431141523931489,0.8540117961671779,-0.4780441382303854,0.1691753905622516
2023-02-22,0.4753018599599933,1.313453733560814,0.23960083165078483,0.2386316408770962



In [46]:
fr.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 0.211134 
 0.907200 
 -0.066232 
 0.195970 
 
 
 std 
 0.602150 
 0.681903 
 1.072597 
 0.842441 
 
 
 min 
 -0.704839 
 -0.347559 
 -1.884717 
 -1.134514 
 
 
 25% 
 -0.141590 
 0.842421 
 -0.383941 
 0.041482 
 
 
 50% 
 0.298110 
 1.007444 
 0.068984 
 0.203904 
 
 
 75% 
 0.689876 
 1.275309 
 0.474491 
 0.364640 
 
 
 max 
 0.843114 
 1.623861 
 1.274615 
 1.496969

In [47]:
fr.T

2023-02-17 
 2023-02-18 
 2023-02-19 
 2023-02-20 
 2023-02-21 
 2023-02-22 
 
 
 
 
 A 
 0.761400 
 -0.704839 
 0.120918 
 -0.229092 
 0.843114 
 0.475302 
 
 
 B 
 1.623861 
 1.160876 
 -0.347559 
 0.838557 
 0.854012 
 1.313454 
 
 
 C 
 -1.884717 
 1.274615 
 -0.101633 
 0.552787 
 -0.478044 
 0.239601 
 
 
 D 
 -1.134514 
 -0.001083 
 0.406643 
 1.496969 
 0.169175 
 0.238632

In [48]:
fr.sort_index(axis=1,ascending=False)

D 
 C 
 B 
 A 
 
 
 
 
 2023-02-17 
 -1.134514 
 -1.884717 
 1.623861 
 0.761400 
 
 
 2023-02-18 
 -0.001083 
 1.274615 
 1.160876 
 -0.704839 
 
 
 2023-02-19 
 0.406643 
 -0.101633 
 -0.347559 
 0.120918 
 
 
 2023-02-20 
 1.496969 
 0.552787 
 0.838557 
 -0.229092 
 
 
 2023-02-21 
 0.169175 
 -0.478044 
 0.854012 
 0.843114 
 
 
 2023-02-22 
 0.238632 
 0.239601 
 1.313454 
 0.475302

In [49]:
fr.sort_values(by="B")

A 
 B 
 C 
 D 
 
 
 
 
 2023-02-19 
 0.120918 
 -0.347559 
 -0.101633 
 0.406643 
 
 
 2023-02-20 
 -0.229092 
 0.838557 
 0.552787 
 1.496969 
 
 
 2023-02-21 
 0.843114 
 0.854012 
 -0.478044 
 0.169175 
 
 
 2023-02-18 
 -0.704839 
 1.160876 
 1.274615 
 -0.001083 
 
 
 2023-02-22 
 0.475302 
 1.313454 
 0.239601 
 0.238632 
 
 
 2023-02-17 
 0.761400 
 1.623861 
 -1.884717 
 -1.134514