In [1]:
import numpy as np

<h1>Krok pierwszy</h1>
To jest pierwszy notebook opisujący bibliotekę numpy

In [2]:
a = 56
b = 44
c = 90
tb = [a,b,c]

for n in tb:
    print(f"______[ - {n} - ]_______")

______[ - 56 - ]_______
______[ - 44 - ]_______
______[ - 90 - ]_______


In [3]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.empty(8)

array([4.65920469e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [6]:
u = np.arange(1,89,3)
print(u)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88]


In [8]:
h = [54,7,3,7,3]
print(type(h))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
k = np.linspace(0,10,num=5)
print(k)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
lt= [6.6,5.,6,True,120,0.09,5e+45]
nplist = np.array(lt)
print(nplist)

[6.6e+00 5.0e+00 6.0e+00 1.0e+00 1.2e+02 9.0e-02 5.0e+45]


In [16]:
kr = {9,3,56,7}
knp = np.array(kr)
print(knp)
print(type(knp))

{56, 9, 3, 7}
<class 'numpy.ndarray'>


In [17]:
nb = [908,23,5,6,8,2,45,63,7,8,35,7,3,6,8,2,24,78,89,9]
nnp = np.array(nb)

In [18]:
nb.sort()
nb

[2, 2, 3, 5, 6, 6, 7, 7, 8, 8, 8, 9, 23, 24, 35, 45, 63, 78, 89, 908]

In [19]:
nnp.sort()
nnp

array([ 2, 2, 3, 5, 6, 6, 7, 7, 8, 8, 8, 9, 23,
 24, 35, 45, 63, 78, 89, 908])

In [20]:
a = np.array([1,5,89,65])
b = np.array([335,78,9])
c = np.array([12,7,8,34,123])

big = np.concatenate((a,b,c))
print(big)

[  1   5  89  65 335  78   9  12   7   8  34 123]


In [21]:
big.sort()
big

array([ 1, 5, 7, 8, 9, 12, 34, 65, 78, 89, 123, 335])

In [28]:
zx = [[5,7],[8,6]]
print(zx)
print(zx[0])
print(zx[0][0])

[[5, 7], [8, 6]]
[5, 7]
5


In [29]:
x = np.array([[67,8],[9,12]])
print(x)
print(x[0,1])

y = np.array([[12,89],[45,58]])

[[67  8]
 [ 9 12]]
8


In [32]:
p = np.concatenate((x,y),axis=0)
p

array([[67, 8],
 [ 9, 12],
 [12, 89],
 [45, 58]])